_wandb:
    value:
        cli_version: 0.17.8
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.17.8
            "8":
                - 1
                - 3
                - 5
            "12": 0.17.8
            "13": windows-amd64
batch_size:
    value: 128
dropout:
    value: 0.15258278555128355
epochs:
    value: 5
lr:
    value: 0.001
